# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

combined_algorithm <- function(lambda, l, r, R0) {
    .Call('_ltic_combined_algorithm', PACKAGE = 'ltic', lambda, l, r, R0)
}

newton_algorithm <- function(lambda, l, r) {
    .Call('_ltic_newton_algorithm', PACKAGE = 'ltic', lambda, l, r)
}

em_algorithm <- function(lambda, l, r, R0) {
    .Call('_ltic_em_algorithm', PACKAGE = 'ltic', lambda, l, r, R0)
}

