# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ltic_r <- function(lambda, l, r, t, R0) {
    .Call('_ltic_ltic_r', PACKAGE = 'ltic', lambda, l, r, t, R0)
}

monotone <- function(x, w) {
    .Call('_ltic_monotone', PACKAGE = 'ltic', x, w)
}

calc_like <- function(lambda, left, right) {
    .Call('_ltic_calc_like', PACKAGE = 'ltic', lambda, left, right)
}

calc_like_lambda <- function(lambda, left, right) {
    .Call('_ltic_calc_like_lambda', PACKAGE = 'ltic', lambda, left, right)
}

calc_derivs <- function(lambda, left, right) {
    .Call('_ltic_calc_derivs', PACKAGE = 'ltic', lambda, left, right)
}

shen_r <- function(s, l, r, t) {
    .Call('_ltic_shen_r', PACKAGE = 'ltic', s, l, r, t)
}

turnbull_r <- function(s, l, r, t) {
    .Call('_ltic_turnbull_r', PACKAGE = 'ltic', s, l, r, t)
}

yu_r <- function(s, l, r, t) {
    .Call('_ltic_yu_r', PACKAGE = 'ltic', s, l, r, t)
}

