# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pava <- function(y, w, np) {
    .Call('_ltic_pava', PACKAGE = 'ltic', y, w, np)
}

combined_algorithm <- function(lambda, l, r, deriv_1_0, R0) {
    .Call('_ltic_combined_algorithm', PACKAGE = 'ltic', lambda, l, r, deriv_1_0, R0)
}

ltic_r <- function(lambda, l, r, t, R0) {
    .Call('_ltic_ltic_r', PACKAGE = 'ltic', lambda, l, r, t, R0)
}

newton_algorithm <- function(lambda, l, r, deriv_1_0) {
    .Call('_ltic_newton_algorithm', PACKAGE = 'ltic', lambda, l, r, deriv_1_0)
}

em_algorithm <- function(lambda, l, r, R0) {
    .Call('_ltic_em_algorithm', PACKAGE = 'ltic', lambda, l, r, R0)
}

monotone <- function(x, w) {
    .Call('_ltic_monotone', PACKAGE = 'ltic', x, w)
}

calc_like <- function(lambda, left, right) {
    .Call('_ltic_calc_like', PACKAGE = 'ltic', lambda, left, right)
}

calc_derivs <- function(lambda, left, right) {
    .Call('_ltic_calc_derivs', PACKAGE = 'ltic', lambda, left, right)
}

